#- alert: Orders Created Decrease 30% for 4 minutes
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[4m]) * 0.7) >
#    last_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[2m])
#    and ((hour() > 1 and hour() < 6))
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "Orders Created Decrease 30% for 4 minutes"
#    description: "Order creation metric dropped by 30% in the last 4 minutes."



#- alert: Orders Created Decrease 50% for 2 minutes
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[2m]) * 0.5) >
#    last_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[2m])
#    and ((hour() > 1 and hour() < 6))
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-sorder
#  annotations:
#    summary: "Orders Created Decrease 50% for 2 minutes"
#    description: "Order creation metric dropped by 50% in the last 2 minutes."



#- alert: Orders Created Decrease 80% for 1 minute
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[1m]) * 0.2) >
#    last_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[2m])
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "Orders Created Decrease 80% for 1 minute"
#    description: "Order creation metric dropped by 80% in the last minute."


#- alert: No Orders Created for 3 intervals
#  expr: >
#    max_over_time(neworder_nats_events_processed{name="order_did_create", namespace="new-order", service="new-order-nats-consumer"}[3m]) == 0
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "No Orders Created for 3 intervals"
#    description: "No orders created in the last 3 monitoring intervals."


#- alert: Active Bids Decrease 30% for 4 minutes
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[4m]) * 0.7) >
#    last_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[2m])
#    and ((hour() > 9 and hour() < 22))  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "Active Bids Decrease 30% for 4 minutes"
#    description: "Active bids metric dropped by 30% in the last 4 minutes."


#- alert: Active Bids Decrease 50% for 2 minutes
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[2m]) * 0.5) >
#    last_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[2m])
#    and ((hour() > 1 and hour() < 6))
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "Active Bids Decrease 50% for 2 minutes"
#    description: "Active bids metric dropped by 50% in the last 2 minutes."


#- alert: Active Bids Decrease 80% for 1 minute
#  expr: >
#    (avg_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[1m]) * 0.2) >
#    last_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[2m])
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "Active Bids Decrease 80% for 1 minute"
#    description: "Active bids metric dropped by 80% in the last minute."


#- alert: No Active Bids for 3 intervals
#  expr: >
#    max_over_time(neworder_nats_events_processed{name="bid_active", namespace="new-order", service="new-order-nats-consumer"}[3m]) == 0
#  labels:
#    severity: critical
#    alert_type: business
#    namespace: new-order
#  annotations:
#    summary: "No Active Bids for 3 intervals"
#    description: "No active bids detected in the last 3 monitoring intervals."