nameOverride: dutyshift

probes:
  readiness:
    enabled: false
  liveness:
    enabled: false
  startup:
    enabled: false

## Additional environment variables for application container
#env:
#  - name: MODFEED_CONFIG
#    value: /app/pagerduty-reminder.config.yaml

## Application container resources
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi


observability:
  enabled: true
  environment: prod-eks-eu-central1
  #alertmanagerConfig: 
  #  enabled: true #включает алерты в pagerduty, но не выключает их в alertmanager
  #prometheusRule:
  #  enabled: true #включает доставку алертов из папки alerts